Project Complete: feature/structure
Elbie-em/JavaScript-Tic-Tac-Toe-Game pull request #2
Opened 2020-07-03 21:42 UTC by Elbie-em

Please follow the map below to see what we worked on. The requirements for this project can be found [here](https://www.theodinproject.com/courses/javascript/lessons/tic-tac-toe-javascript).
* Set up project with an HTML, CSS and JavaScript files
* Added Linter configurations and files for JavaScript(eslint) and CSS(style lint)
* Built functions that allow players to add marks to a specific cell on the board, and then tie it to the DOM, letting players click on the game board to place their marker.
* Built logic that checks when the game is over by declaring a winner or tie.
* Cleaned up the interface to allow players to put in their names, included a button to start/restart the game and add a display element that congratulates the winning player!
* Added validation in input form.

2020-07-05 10:54 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @Elbie-em @abdelp 

You did a really nice job.
Nothing really to say except some small changes to do.

Kindly read the comments left below and apply them. Then, submit a new code review request.
Thanks

Mael FOSSO

2020-07-05 10:54 UTC, maelfosso commented on js/modules/game.js
> +export { Game }; // eslint-disable-line import/prefer-default-export
Please, re-enable that configuration and apply a default export.

2020-07-05 10:54 UTC, maelfosso commented on js/index.js
> +const Player = (id, name, symbol) => ({ id, name, symbol });
Move it into `game.js`

2020-07-05 10:54 UTC, maelfosso commented on js/index.js
> +const Player = (id, name, symbol) => ({ id, name, symbol });
Make the `game.js` file the module with no code related to DOM.
I mean code with only Logic, controller, etc...
And into `index.js` only DOM manipulation in respect to the output of `game.js`

2020-07-09 16:26 UTC, abdelp commented
Fixed all of the issues moving the DOM manipulation to the doman.js module

2020-07-09 17:31 UTC, whiz25 approved these changes
## Approved! :clap: 
You have the requested changes and it's a :+1:  from me. Merge and proceed to next milestone.

### Martin Afani

2020-07-09 19:05 UTC, merged